### ISSUE TITLE
Add to the "right" catalog in the "right" place

### ISSUE THREAD

**Issue by mslw** [sfb1451/tabby-utils#1]
The `load_tabby` script currently adds metadata to a catalog in its working directory, just to form a preview. We need a way to add the entries to the pre-tabby catalog (https://github.com/psychoinformatics-de/sfb1451-projects-catalog) so that tabby-dataset entries land in correct places (i.e. under respective projects).

This can be done within the load_tabby script. Alternatively, the load_tabby script would write its outputs to a json-lines file, and another script would handle adding.

In principle, this would require two steps:
- add the metadata item(s) from tabby
- add a metadata item containing `subdatasets: {dataset_id: ..., dataset_version:..., dataset_path:...}` with values representing tabby-subdataset, and `{dataset_id:..., datast_version}` of a parent dataset.

The above would work from a purely catalog standpoint (we are saying that this tabby metadata should be displayed as a subdataset of that dataset), but it violates the DataLad versioning nature (adding a subdataset declaration would normally progress the parent dataset state). A more kosher approach would be to deposit tabby (tsv) files in the parent dataset, and have two extractors: one would do everything that load_tabby does now (i.e. read tabby contents), and another would create the subdataset statement (similar to what metalad_core does to submodules).

**Comment by mslw** [comment]
From a procedural standpoint, for https://github.com/psychoinformatics-de/sfb1451-projects-catalog, I think we can assume that:

- tabby files will be placed in their respective parent dataset (project's superdataset)
- there is no tabby nesting more than one level deep
- the `load_tabby` script will be pointed to a tabby file (with an argparse argument), as it is now
- the script needs to find the parent dataset (there should be some ready datalad method?)
- the script needs to produce metadata items from tabby plus one metadata item for parent dataset (as explained in top comment)
- the script needs to output its metadata to a file, or add it straight to catalog

For that catalog instance in particular, this would mean that we update all project superdatasets with tabby files. There will be some half-manual work (scripted in that repo) with regenerating dataset metadata (some comes from cff files, some from external input etc.) but it would be manageable.

**Comment by jsheunis** [comment]
Some comments/questions:

Firstly, regarding the location of tabby files in the project superdatasets. This is something that I remember was confusing for me at some point, but I can't remember what the resolution looked like. Will we add tabby files as a subdataset to each project superdataset (e.g. in a generic `tabby` directory), e.g.:

```
Project A
.
├── publications
│   ├── blabla.json
│   └── foobar.ris
├── some_subdataset_with_data
├── tabby
│   ├── dataset@tby-crc1451v0.tsv
│   ├── files@tby-crc1451v0.tsv
│   ├── ...
│   ├── data-controller@tby-crc1451v0.tsv
│   └── authors@tby-crc1451v0.tsv
└── CITATION.cff
```

And do we also want this to be displayed exactly like that in the catalog? I.e. the `tabby` directory would be shown as a subdataset (in the subdatasets tab). In addition, the metadata extracted from the tabby files would be added to the project dataset itself, on the same level at which the `CITATION.cff` metadata is added?

Am I understanding this all correctly?

**Comment by jsheunis** [comment]
Oh no, I just realised my error. The point is that any tabby addition would be a new subdataset, similar to what an existing subdataset such as `some_subdataset_with_data` is.

So my assumption now is:
- tabby files themselves wont appear in the catalog
- the subdataset described by the tabby files will appear in the catalog

**Comment by mih** [comment]
I am in agreement with pretty much anything that is stated here. I just want to point out that a `tabby` record placed in a dataset should be interpreted as **equivalent** to a subdataset and **not as an actual subdataset** (or be a subdataset) -- all from a metadata reporting point of view.

Eventually there should be no need for any non-standard scripts. Reading a tabby record from a dataset is nothing different from reading any metadata from a dataset. There should be a `tabby` extractor for that. And that extractor would report any `tabby` metadata it finds (for the parent dataset and/or tabby "subdatasets"). It will be the extractors task to define how things like "mountpoints" of such a virtual subdataset are defined. The tabby code already support one-record-per-directory layouts that could be used to arrange records in a "shadow-tree" under a declared "tabby root" directory.

**Comment by mslw** [comment]
> Oh no, I just realised my error. The point is that any tabby addition would be a new subdataset, similar to what an existing subdataset such as `some_subdataset_with_data` is.

Yes. So if tabby files go into `tabby_something_dataset`, that is to be seen is in a way similar to a declaration in `.gitmodules` - that there is a `tabby_something_dataset` subdataset. But the files themselves are tracked under Project A dataset.

At least that is my mental model.

> 
> So my assumption now is:
> 
>     * tabby files themselves wont appear in the catalog

They may or may not (hard to avoid them if we run a files extractor on the Project dataset, but currently we don't do that). But whether they do or do not appear in the catalog is of little relevance.

>     * the subdataset described by the tabby files will appear in the catalog

Yes, that is the number 1 thing that we care about.

**Comment by mih** [comment]
> They may or may not (hard to avoid them if we run a files extractor on the Project dataset, but currently we don't do that). But whether they do or do not appear in the catalog is of little relevance.

I agree. Moreover, I see no reason to filter them out. This would require the catalog tooling to be aware of this particular type of metadata (a cost without a gain). We also do not strip a BIDS dataset's `participants.tsv`, just because we know that it is metadata.

**Comment by mslw** [comment]
> the script needs to find the parent dataset (there should be some ready datalad method?)
the script needs to produce metadata items from tabby plus one metadata item for parent dataset (as explained in top comment)

Added in c89afdd

**Comment by mslw** [comment]
> > the script needs to find the parent dataset (there should be some ready datalad method?)
> > the script needs to produce metadata items from tabby plus one metadata item for parent dataset (as explained in top comment)
> 
> Added in [c89afdd](https://github.com/mslw/tabby-utils/commit/c89afdd0fa7b41ca824df77ee1d2232e31a4736b)

While the `load_tabby` script now takes care of updating the superdataset's list of subdatasets, it's worth remembering that all dataset metadata are versioned. So if a superdataset receives new commits, re-extracting its metadata (which in practice always includes metalad core) would remove the link to the tabby dataset - which itself needs no metadata update because it remains unchanged.

It would seem that the easiest fix would be to isolate the "linkage" step into its own operation, done on the superdataset. The problem is, it needs to be aware of the subdataset's ID (involves both a method of generating and the input from tabby file)...

I am now starting to suffer from the fragmentation of all the tools - one for loading tabby, one for loading non-tabby, ...

**Comment by mslw** [comment]
I was not doing it consistently in the past (i.e. with the first round of tabby submissions), but it seems that we would now prefer to organize tabby file collections under `.datalad/tabby/collection-name`.

Paths under `.datalad/tabby` can be used to specify subdataset paths or even subdataset nesting, although we don't have a specific convention in place, yet.

**Comment by mslw** [comment]
No nesting defined for `.datalad/tabby` yet, but describing the superdataset relation has been delegated to a separate script, `load_subdatasets.py`, in #12. It contains heuristics for building dataset paths regardless of whether `.datalad/tabby` is used or not (has a CLI flag to enable searching anywhere).

So the recommended procedure would now be:
- place tabby files in `.datalad/tabby` using `load_inbox.py`
- extract tabby files using `load_tabby.py`
- add the super-subdataset linkage with `load_subdatasets.py`

I think this is sufficient for the current structure.
