### ISSUE TITLE
Semantic catalog tab - a proposal

### ISSUE THREAD

**Issue by mslw** [sfb1451/tabby-utils#14]
### Context
- DataLad Catalog can take `additional_display` metadata field, and display its contents (key-value pairs) as an additional tab with a table (where keys define the first column and values the second). However, any object (string, array, dict) is displayed in the table as its plain string representation.
- A custom patch was introduced for SFB1451 catalog, which allows the table to display links (for both keys and values). The links or data types can be provide in a separate `additional_display_definitions`: https://github.com/psychoinformatics-de/sfb1451-projects-catalog/pull/56,
- The custom patch necessitates first creating and then reading two interdependent objects.
- I propose defining a *semantic tab* (or additional semantic display), which would require a single object to be provided.

### Proposed solution

The semantic tab would still be based on `additional_display`, with key-value pairs. This object would additionally contain a json-ld `@context` definition for its fields, and its contents would be objects that have a `@type` property or arrays of such objects (or strings, arrays of strings). The catalog JS code would define handling for a set of known types, and default to string representation if the type is unknown or not declared.

### Practical overview

These are all the SFB-specific fields that are defined in [data catalog submission docs](https://rdm.sfb1451.de/data-catalog-submission/). Listed properties either are or could be [^1] defined when processing tabby files with code in this repo. The following types can describe their values (either inferred or declared explicitly).

| thingy | property | type | show as |
| --- | --- | --- | --- |
| Homepage | [mainEntityOfPage](https://schema.org/mainEntityOfPage) | [URL](https://schema.org/URL) | link |
| Data Controller | [dpv#hasDataController](https://w3id.org/dpv#hasDataController) | [Person](https://schema.org/Person) / [Organization](https://schema.org/Organization) / [ContactPoint](https://schema.org/ContactPoint) [^2] | link (e-mail) |
| Used For | [prov#hadUsage](http://www.w3.org/ns/prov#hadUsage) | ??? | text |
| Project | [ResearchProject](https://schema.org/ResearchProject) [^3] | [ResearchProject](https://schema.org/ResearchProject) | text
| Sample Organism | [Species](https://openminds-documentation.readthedocs.io/en/latest/specifications/controlledTerms/species.html) |  [Species](https://openminds-documentation.readthedocs.io/en/latest/specifications/controlledTerms/species.html) | link (custom-formatted text) |
| Sample Part | [UberonParcellation](https://openminds-documentation.readthedocs.io/en/latest/specifications/controlledTerms/UBERONParcellation.html) | [UBERONParcellation](https://openminds-documentation.readthedocs.io/en/latest/specifications/controlledTerms/UBERONParcellation.html) | link (custom-formatted text)

### Comment on types

Apart from two openminds types, Species and UBERONParcellation, other types come from schema.org and are fairly generic, therefore could be useful for DataLad Catalog in general. However, we are already patching the SFB catalog with custom handlers, so why not add those two as well? They would serve rendering very nicely, because they include properties such as `name`, `synonym`, and `preferredOntologyIdentifier`, see e.g. [Mus musculus](https://openminds-documentation.readthedocs.io/en/latest/libraries/terminologies/species.html#musmusculus) (house mouse can be a synonym).

### Implementation

A dictionary with `@type` and context could be generated in `load_tabby` (in this repo). All IRIs would ideally be given in an expanded form (i.e. no `schema:Person`) to avoid having to go through expansion. Processing the table in JS+html could be done in a way analogous to the currently implemented patch (see above). Links displayed next to row keys would probably come from context. I will work on a solution in the next working day.

### Related issues

https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/60 was direct inspiration
https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/41 was the original problem statement

[^1]: SampleOrganism and SamplePart currently use other definitions but the proposed approach favours redefinition; see #10 for more information
[^2]: Technically the former two can be data controllers, but we care about name & email, properties present in these three schema types
[^3]: Technically a Type, so may need to change

**Comment by jsheunis** [comment]
This sounds like a sensible suggestion and outline. I'm trying to get a concrete idea of what such an addition to the catalog schema would look like, so let's work on an example of such metadata.

First an example of the current data structure with `additional_display` and `additional_display_definitions` as two separate fields in a `dataset` [metadata record](https://github.com/psychoinformatics-de/sfb1451-projects-catalog/blob/main/docs/metadata/11e6d90c-08a0-5acb-bf19-fc81a1472355/Latest/56f/fb4051dbfca0e7a167fe22b1ebf20.json):

```json
{
    "type": "dataset",
    "dataset_id": "11e6d90c-08a0-5acb-bf19-fc81a1472355",
    "dataset_version": "Latest",
    ...
    "additional_display": [
        {
            "name": "SFB1451",
            "icon": "fa-solid fa-flask",
            "content": {
                "CRC project": "Z02",
                "data controller": {
                    "email": "graziana.gatto@uk-koeln.de",
                    "name": "Graziana Gatto "
                },
                "sample (organism)": "house mouse (Mus musculus; NCBITaxon_10090)",
                "sample (organism part)": "skeletal joint (UBERON_0000982)"
            }
        }
    ],
    "additional_display_definitions": {
        "SFB1451": {
            "keys": {
                "homepage": "https://schema.org/mainEntityOfPage",
                "CRC project": "https://schema.org/ResearchProject",
                "data controller": {
                    "self": "https://w3id.org/dpv#hasDataController",
                    "email": "https://schema.org/email",
                    "name": "https://schema.org/name"
                },
                "sample (organism)": "https://purl.obolibrary.org/obo/UBERON_0000468",
                "sample (organism part)": "https://purl.obolibrary.org/obo/UBERON_0000475",
                "Used for": "http://www.w3.org/ns/prov#hadUsage"
            },
            "values": {
                "homepage": "https://schema.org/URL",
                "CRC project": "https://schema.org/Text",
                "data controller": {
                    "email": "https://schema.org/Text",
                    "name": "https://schema.org/Text"
                },
                "sample (organism)": "http://purl.obolibrary.org/obo/NCBITaxon_10090",
                "sample (organism part)": "http://purl.obolibrary.org/obo/UBERON_0000982",
                "Used for": "https://schema.org/Text"
            }
        }
    }
}
```

So the question is, how would this data look like in the updated version?

**Comment by jsheunis** [comment]
This is what I currently have as an example of the semantic metadata with `@context` and `@type`:

```json
{
    "type": "dataset",
    "dataset_id": "11e6d90c-08a0-5acb-bf19-fc81a1472355",
    "dataset_version": "Latest",
    ...
    "additional_display": [
        {
            "name": "SFB1451",
            "icon": "fa-solid fa-flask",
            "content": {
                "@context": {
                    "homepage": {
                        "@id": "https://schema.org/mainEntityOfPage",
                        "@type": "http://schema.org/URL"
                    },
                    "CRC project": {
                        "@id": "http://schema.org/ResearchProject",
                        "@type": "http://schema.org/Text"
                    },
                    "data controller": {
                        "@id": "https://w3id.org/dpv#hasDataController"
                    },
                    "data controller:email": {
                        "@id": "http://schema.org/email",
                        "@type": "http://schema.org/URL"
                    },
                    "data controller:name": {
                        "@id": "http://schema.org/name",
                        "@type": "http://schema.org/Text"
                        
                    },
                    "sample (organism)": {
                        "@id": "https://purl.obolibrary.org/obo/UBERON_0000468",
                        "@type": "http://purl.obolibrary.org/obo/NCBITaxon_10090"
                    },
                    "sample (organism part)": {
                        "@id": "https://purl.obolibrary.org/obo/UBERON_0000475",
                        "@type": "http://purl.obolibrary.org/obo/UBERON_0000982"
                    }
                },
                "CRC project": "Z02",
                "data controller": {
                    "email": "graziana.gatto@uk-koeln.de",
                    "name": "Graziana Gatto "
                },
                "sample (organism)": "house mouse (Mus musculus; NCBITaxon_10090)",
                "sample (organism part)": "skeletal joint (UBERON_0000982)"
            }
        }
    ]
}
```

Some rules/assumptions:
- if `additional_display[i]["content"]` has the field `@context`, then this is interpreted and rendered as a tab with semantic metadata
- `additional_display[i]["content"]["@context"][<some-property>]["@id"]` provides the definition of the property
- `additional_display[i]["content"]["@context"][<some-property>]["@value"]` provides the definition of the property's value
- values that map directly onto some standard rendering method include:
   - http://schema.org/Text
   - http://schema.org/URL
- if the value is not in the list of standard renderable values, assume that the value should be rendered as a link to the provided url

**Comment by mslw** [comment]
Thanks a lot for these comments and examples!

I'll try to first get something done in practice (to see if some problems become apparent only in the implementation) and then try to comment in more detail. I imagined the semantic metadata somewhat differently. Key difference the usage of `@id` and `@type`, and where they go. Ultimately, this is a question of how they should be used in json-ld [^1]. Also (this may be an issue with notation - is `data controller:email` a standard way to write an object?) I wanted to use mostly objects rather than separate their values.

So (picking only parts of your example), I would rather go for something like:

``` json
{
    "type": "dataset",
    "dataset_id": "11e6d90c-08a0-5acb-bf19-fc81a1472355",
    "dataset_version": "Latest",
    "additional_display": [
        {
            "name": "SFB1451",
            "icon": "fa-solid fa-flask",
            "content": {
                "@context": {
                    "data controller": "https://w3id.org/dpv#hasDataController",
                    "sample (organism)": "https://openminds.ebrains.eu/controlledTerms/Species"
                },
                "data controller": {
                  "@type": "https://schema.org/Person",
                  "name": "John Doe",
                  "email": "jdoe@example.com"
                },
                "sample (organism)": {
                  "@id": "https://openminds.ebrains.eu/instances/species/musMusculus",
                  "@type": "https://openminds.ebrains.eu/controlledTerms/Species",
                  "name": "Mus musculus",
                  "synonym": "house mouse",
                  "preferredOntologyIdentifier": "http://purl.obolibrary.org/obo/NCBITaxon_10090",
                }
            }
          }
    ]
}
```

Small comment 1: I'm not annotating the type of email, but https://schema.org/Person tells me its expected type is Text.
Small comment 2: I'm using Species in two meanings (in context and in type) which is probably not good, ideally context would use some *property* name, like `containsDataFromSpecies" (invented by me)

[^1]: I found, but did not fully process, https://stackoverflow.com/questions/24318237/what-is-the-difference-between-json-ld-id-and-type-in-the-context

**Comment by jsheunis** [comment]
> Key difference the usage of @id and @type, and where they go. Ultimately, this is a question of how they should be used in json-ld

I admit that my understanding of this is far from complete, so I wouldn't be surprised if my suggested approach is not ideal.

> this may be an issue with notation - is data controller:email a standard way to write an object?

Looks like it is yes, when looking at the examples in the JSON-LD playground, e.g. `event`:

```
{
  "@context": {
    "ical": "http://www.w3.org/2002/12/cal/ical#",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "ical:dtstart": {
      "@type": "xsd:dateTime"
    }
  },
  "ical:summary": "Lady Gaga Concert",
  "ical:location": "New Orleans Arena, New Orleans, Louisiana, USA",
  "ical:dtstart": "2011-04-09T20:00:00Z"
}
```

but your approach is also standard, looking at the `activity` example in the playground.

> Small comment 1: I'm not annotating the type of email, but https://schema.org/Person tells me its expected type is Text.

This has implications for the rendering side in javascript, specifically if fields with yet to be resolved definitions have to be rendered, i.e. they would have to be resolved within the javascript code (not ideal in the current use case, but perhaps something that's inevitable for the future of the catalog?) or some default `@type` would have to be assumed.

**Comment by mslw** [comment]
Two immediate follow-ups with my current thinking:

I re-read that Stackoverflow comment, `@type` in context means "how to handle plain-string values of that term used within the body". So all in all, there's several ways to put it...

Back to Person / e-mail, I imagine renderer to work with a Person as a whole (assuming expected types from schema.org). If I understand correctly, you could do types all the way down, like:

```
"data controller": {
    "@type": "https://schema.org/Person",
    "name":  {"@type": "https://schema.org/text", "@value": "John Doe"},
    "email": {"@type": "https://schema.org/text", "@value": "jdoe@example.com"},
  }
```
but still it would be up to the renderer to decide "It's a person with name and e-mail - show as a mailto link". FWIW, https://schema.org/Person#eg-0001 (JSON-LD) does not annotate `@type` for e-mail (text literal), but it does for address (obkject).
