### ISSUE TITLE
Isolating processing steps: tabby to catalog

### ISSUE THREAD

**Issue by jsheunis** [sfb1451/tabby-utils#4]
I'm trying to isolate the steps that are necessary to go from raw tabby files in the "inbox" to a populated catalog rendering. Mostly for my own understanding, but also to get to a point where we can more easily say which components should form part of which tool or process. This is my current understanding:

1. Custom file handling that is particular to CRC1451 (but which would likely form part of any similar pipeline) to:
   - rename any tabby files with typos/errors
   - add a convention suffix to each tabby file
   - move related tabby files into dedicated and uniquely named directories (crc1451 projects)
2. Load tabby file(s) into `json` format using `datalad-tabby`
3. Expand the loaded document using `jsonld.expand`
4. Compact the expanded document, together with a custom provided context, using `jsonld.compact` (the context provided as part of the convention does not cover all terms to be interpreted and injected into the cataloging process)
5. Generate a dataset-level metadata item for the catalog, which involves in order:
   - creating an empty dataset dictionary with the structure required by the catalog and with some standard fields pre-filled (e.g. ID, metadata sources) by using custom utility functions in `tabby-utils`
   - translating fields from the loaded/expanded/compacted tabby document into corresponding fields of the dataset dictionary (using custom utility functions in `tabby-utils`)
6. If provided via the tabby document, generate file-level metadata items for the catalog, which involves in order:
   - creating an empty file dictionaries with the structure required by the catalog and with some standard fields pre-filled (e.g. parent ID) by using custom utility functions in `tabby-utils`
   - translating fields from the loaded/expanded/compacted tabby document into corresponding fields of the file dictionary (using custom utility functions in `tabby-utils`)
   - adding the file-level metadata item to a list for later iteration
7. Add dataset- and file-level metadata to a catalog by using `datalad-catalog` functionality

Utility functionalities include:
- creating a deterministic dataset ID based on a custom convention
- generating baseline dictionaries/documents with standard fields required by the catalog (e.g. `metadata_sources` or empty structures for a `dataset` or a `file`)
- linking catalog file metadata to catalog dataset metadata via the required fields
- querying available APIs for more information about a specific term or argument (e.g. authors and title from DOI, definitions of terms in ontologies)

**Comment by jsheunis** [comment]
Most of the custom code involves:

1. Generating baseline dictionaries/documents with standard fields required by the catalog (e.g. metadata_sources or empty structures for a dataset or a file)
   - To me it make most sense to put this helper functionality into `datalad-catalog`, then this would evolve and be maintained together with the catalog schema in the same place.
2. Translation:
   - I feel like this is where we can make a lot of gains when we consider the possibilities of semantic metadata and json-ld processing. If the catalog is updated to be truly capable of recognizing terms from different ontologies and rendering these appropriately, then any translation steps done before passing the document to the catalog could be minimized. I have to think about this more in order to make it make sense more, though.

**Comment by mslw** [comment]
Just a short comment: I think that captures the current process well.

**Comment by jsheunis** [comment]
> 1. Generating baseline dictionaries/documents with standard fields required by the catalog (e.g. metadata_sources or empty structures for a dataset or a file)
>   - To me it make most sense to put this helper functionality into datalad-catalog, then this would evolve and be maintained together with the catalog schema in the same place.

Issue in datalad-catalog: https://github.com/datalad/datalad-catalog/issues/346

**Comment by jsheunis** [comment]
@mslw I will close this issue as it was mainly for discussion and no concrete TODOs except for where issues have already been created in the appropriate venues.
