### ISSUE TITLE
Move to sfb1451 org?

### ISSUE THREAD

**Issue by jsheunis** [sfb1451/tabby-utils#5]
In order to make coordination simpler:

It seems to me that not all code in this repo pertains to `tabby`, but rather to the sfb145 catalog generation process, wherein `tabby` plays a role. So I suggest this repo could be called `sfb1451-utils` and moved to the `sfb1451` org. Alternatively, the issues and code here could be merged with https://github.com/psychoinformatics-de/sfb1451-projects-catalog, and the repo also moved to the `sfb1451` org (with/without renaming).

**Comment by jsheunis** [comment]
Relevant links for context:
- https://github.com/sfb1451
- https://github.com/psychoinformatics-de/rfd/pull/68
- https://github.com/psychoinformatics-de/sfb1451-projects-catalog
- https://rdm.sfb1451.de/

**Comment by mslw** [comment]
This repo is now in the sfb1451 org.

Since it contains code tuned for sfb1451, but focusing on handling tabby data, I will keep the tabby-utils name.
